import '../scss/fonts.scss'
import '../scss/reset.scss'

import '../scss/general.scss'
import '../scss/aboutUs.scss'
import '../scss/header.scss'
import '../scss/appliences.scss'
import '../scss/footer.scss'
import '../scss/modalFeedback.scss'
import '../scss/modalTel.scss'
import '../scss/modalMenu.scss'
import '../scss/prices.scss'
import '../scss/repair.scss'
// import '../scss/style.scss'

import '../js/appliencesShowAllBtn.js'
import '../js/burgerMenu.js'
import '../js/repairShowAllBtn.js'
import '../js/slider.js'
import '../js/modalFeedback.js'
import '../js/modalTel.js'